<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musicos [
    <!ELEMENT musicos (musico*)>
    <!ELEMENT musico ((nombre|apodo),fechaNacimiento)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apodo (#PCDATA)>
    <!ELEMENT fechaNacimiento (#PCDATA)>
]>

<musicos>
    <musico>
        <apodo>El cura pelirrojillo</apodo>
        <fechaNacimiento>4 de marzo de 1678</fechaNacimiento>
    </musico>
    <musico>
        <apodo>El viejo peluca</apodo>
        <fechaNacimiento>21 de marzo de 1685</fechaNacimiento>
    </musico>
</musicos>

<!-- Arriba se especifica que solo puede estar o el nombre o el apodo,por lo que se elimina uno de
los dos -->