<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
    <!ELEMENT agenda (contacto*)>
    <!ELEMENT contacto (nombre,telefonoFijo*,telefonoMovil+)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT telefonoFijo (#PCDATA)>
    <!ELEMENT telefonoMovil (#PCDATA)>
]>

<agenda>
    <contacto>

        <nombre>Ayuntamiento</nombre>
        <telefonoFijo>010</telefonoFijo>
        <telefonoMovil>66666</telefonoMovil>

    </contacto>
    <contacto>

        <nombre>Emergencias</nombre>
        <telefonoFijo>112(Union Europea)</telefonoFijo>
        <telefonoFijo>911(Estados Unidos)</telefonoFijo>
        <telefonoMovil>Desconocido</telefonoMovil>

    </contacto>
</agenda>

<!-- Falta un telefono movil ya que el + indica que puede ser minimo 1 y maximo infinito,
en el segundo estan mal ordenadas las etiquetas,tienen que seguir el orden indicado arriba -->