<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligaDeFutbol [
    <!ELEMENT ligaDeFutbol (partido*)>
    <!ELEMENT partido (local, visitante)>
    <!ELEMENT local (nombre)>
    <!ELEMENT visitante (nombre)>
    <!ELEMENT nombre (#PCDATA)>
    <!ATTLIST local goles CDATA #REQUIRED>
    <!ATTLIST visitante goles CDATA #REQUIRED>
]>
<ligaDeFutbol>
    <partido>
        <local goles="0">
            <nombre>Nottingham Presa</nombre>
        </local>
        <visitante goles="1">
            <nombre>Inter de Mitente</nombre>
        </visitante>
    </partido>
    <partido>
        <local goles="3">
            <nombre>Vodka Juniors</nombre>
        </local>
        <visitante goles="3">
            <nombre>Sparta da Risa</nombre>
        </visitante>
    </partido>
    <partido>
        <local goles="4">
            <nombre>Water de MÃºnich</nombre>
        </local>
        <visitante goles="2">
            <nombre>Esteaua es del grifo</nombre>
        </visitante>
    </partido>
</ligaDeFutbol>